/** Step 1 ülke seçimi: Türkiye önce, sonra yaygın ülkeler (alfabetik) */
export const COUNTRY_OPTIONS: { value: string; label: string; labelEn: string }[] = [
  { value: 'TR', label: 'Türkiye', labelEn: 'Turkey' },
  { value: 'DE', label: 'Almanya', labelEn: 'Germany' },
  { value: 'US', label: 'Amerika Birleşik Devletleri', labelEn: 'United States' },
  { value: 'GB', label: 'Birleşik Krallık', labelEn: 'United Kingdom' },
  { value: 'AZ', label: 'Azerbaycan', labelEn: 'Azerbaijan' },
  { value: 'NL', label: 'Hollanda', labelEn: 'Netherlands' },
  { value: 'FR', label: 'Fransa', labelEn: 'France' },
  { value: 'KZ', label: 'Kazakistan', labelEn: 'Kazakhstan' },
  { value: 'SA', label: 'Suudi Arabistan', labelEn: 'Saudi Arabia' },
  { value: 'CH', label: 'İsviçre', labelEn: 'Switzerland' },
  { value: 'IT', label: 'İtalya', labelEn: 'Italy' },
  { value: 'ES', label: 'İspanya', labelEn: 'Spain' },
  { value: 'SE', label: 'İsveç', labelEn: 'Sweden' },
  { value: 'AT', label: 'Avusturya', labelEn: 'Austria' },
  { value: 'BE', label: 'Belçika', labelEn: 'Belgium' },
  { value: 'CA', label: 'Kanada', labelEn: 'Canada' },
  { value: 'EG', label: 'Mısır', labelEn: 'Egypt' },
  { value: 'GR', label: 'Yunanistan', labelEn: 'Greece' },
  { value: 'IR', label: 'İran', labelEn: 'Iran' },
  { value: 'IQ', label: 'Irak', labelEn: 'Iraq' },
  { value: 'JP', label: 'Japonya', labelEn: 'Japan' },
  { value: 'JO', label: 'Ürdün', labelEn: 'Jordan' },
  { value: 'KG', label: 'Kırgızistan', labelEn: 'Kyrgyzstan' },
  { value: 'LB', label: 'Lübnan', labelEn: 'Lebanon' },
  { value: 'PK', label: 'Pakistan', labelEn: 'Pakistan' },
  { value: 'PL', label: 'Polonya', labelEn: 'Poland' },
  { value: 'RU', label: 'Rusya', labelEn: 'Russia' },
  { value: 'SY', label: 'Suriye', labelEn: 'Syria' },
  { value: 'TM', label: 'Türkmenistan', labelEn: 'Turkmenistan' },
  { value: 'UA', label: 'Ukrayna', labelEn: 'Ukraine' },
  { value: 'UZ', label: 'Özbekistan', labelEn: 'Uzbekistan' },
  { value: 'OTHER', label: 'Diğer', labelEn: 'Other' },
]
