-- Sample Registration Logs
-- Test için örnek log verileri

INSERT INTO registration_logs (
  registration_id, 
  ip_address, 
  ip_version,
  user_agent,
  browser_name,
  browser_version,
  os_name,
  os_version,
  device_type,
  referrer,
  referrer_domain,
  utm_source,
  utm_medium,
  utm_campaign,
  form_started_at,
  form_completed_at,
  form_duration_seconds,
  screen_resolution,
  language,
  timezone,
  country_name,
  city,
  is_proxy,
  is_vpn,
  is_tor,
  risk_score
) VALUES
-- Normal desktop kullanıcı
(
  (SELECT id FROM registrations ORDER BY id DESC LIMIT 1),
  '185.123.45.67',
  'IPv4',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Chrome',
  '120.0.0.0',
  'Windows',
  '10',
  'desktop',
  'https://google.com/search?q=kayit+formu',
  'google.com',
  'google',
  'organic',
  NULL,
  NOW() - INTERVAL 5 MINUTE,
  NOW(),
  300,
  '1920x1080',
  'tr-TR',
  'Europe/Istanbul',
  'Turkey',
  'Istanbul',
  FALSE,
  FALSE,
  FALSE,
  10
),
-- Mobile kullanıcı
(
  (SELECT id FROM registrations ORDER BY id DESC LIMIT 1 OFFSET 1),
  '78.190.23.145',
  'IPv4',
  'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
  'Safari',
  '17.0',
  'iOS',
  '17.0',
  'mobile',
  'https://facebook.com',
  'facebook.com',
  'facebook',
  'social',
  'summer_campaign',
  NOW() - INTERVAL 10 MINUTE,
  NOW() - INTERVAL 2 MINUTE,
  480,
  '390x844',
  'tr-TR',
  'Europe/Istanbul',
  'Turkey',
  'Ankara',
  FALSE,
  FALSE,
  FALSE,
  5
),
-- VPN kullanıcı (şüpheli)
(
  (SELECT id FROM registrations ORDER BY id DESC LIMIT 1 OFFSET 2),
  '104.28.15.89',
  'IPv4',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
  'Chrome',
  '119.0.0.0',
  'Mac OS',
  '10.15.7',
  'desktop',
  'direct',
  NULL,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL 3 MINUTE,
  NOW(),
  180,
  '2560x1440',
  'en-US',
  'America/New_York',
  'United States',
  'New York',
  FALSE,
  TRUE,
  FALSE,
  65
);
