-- Test POS İşlemleri
-- Bu script test amaçlı POS işlem kayıtları ekler

-- Başarılı işlem
INSERT INTO online_payment_transactions (
  registration_id,
  transaction_id,
  order_id,
  amount,
  currency,
  status,
  payment_status,
  gateway_name,
  bank_name,
  card_type,
  card_last4,
  card_bin,
  installment,
  cardholder_name,
  ip_address,
  is_3d_secure,
  threeds_status,
  eci,
  fraud_score,
  fraud_status,
  user_agent,
  session_id,
  gateway_request,
  gateway_response,
  initiated_at,
  completed_at,
  callback_received_at,
  created_at
) VALUES (
  1,
  'TXN_SUCCESS_001',
  'ORD_2024_001',
  2500.00,
  'TRY',
  'success',
  'approved',
  'Test Gateway',
  'Ziraat Bankası',
  'VISA',
  '7894',
  '454671',
  1,
  'TEST KULLANICI',
  '192.168.1.100',
  TRUE,
  'Y',
  '05',
  15,
  'approved',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  'sess_test_001',
  '{"card_number": "454671******7894", "amount": 2500.00, "currency": "TRY"}',
  '{"status": "success", "code": "00", "message": "İşlem başarılı", "transaction_id": "TXN_SUCCESS_001"}',
  NOW() - INTERVAL 5 MINUTE,
  NOW() - INTERVAL 2 MINUTE,
  NOW() - INTERVAL 2 MINUTE,
  NOW() - INTERVAL 5 MINUTE
);

-- Başarısız işlem - Geçersiz İşlem (CVV: 120)
INSERT INTO online_payment_transactions (
  registration_id,
  transaction_id,
  order_id,
  amount,
  currency,
  status,
  payment_status,
  error_code,
  error_message,
  gateway_name,
  bank_name,
  card_type,
  card_last4,
  card_bin,
  installment,
  cardholder_name,
  ip_address,
  is_3d_secure,
  fraud_score,
  fraud_status,
  user_agent,
  session_id,
  gateway_request,
  gateway_response,
  notes,
  initiated_at,
  created_at
) VALUES (
  1,
  'TXN_FAILED_001',
  'ORD_2024_002',
  3500.00,
  'TRY',
  'failed',
  'declined',
  '12',
  'Geçersiz İşlem',
  'Test Gateway',
  'Ziraat Bankası',
  'VISA',
  '7894',
  '454671',
  1,
  'TEST KULLANICI',
  '192.168.1.101',
  FALSE,
  25,
  'review',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
  'sess_test_002',
  '{"card_number": "454671******7894", "cvv": "120", "amount": 3500.00, "currency": "TRY"}',
  '{"status": "failed", "code": "12", "message": "Geçersiz İşlem", "transaction_id": "TXN_FAILED_001"}',
  'Test: CVV 120 kullanıldı',
  NOW() - INTERVAL 10 MINUTE,
  NOW() - INTERVAL 10 MINUTE
);

-- Başarısız işlem - Geçersiz Tutar (CVV: 130)
INSERT INTO online_payment_transactions (
  registration_id,
  transaction_id,
  order_id,
  amount,
  currency,
  status,
  payment_status,
  error_code,
  error_message,
  gateway_name,
  bank_name,
  card_type,
  card_last4,
  card_bin,
  installment,
  cardholder_name,
  ip_address,
  is_3d_secure,
  fraud_score,
  fraud_status,
  user_agent,
  session_id,
  gateway_request,
  gateway_response,
  notes,
  initiated_at,
  created_at
) VALUES (
  1,
  'TXN_FAILED_002',
  'ORD_2024_003',
  1500.00,
  'TRY',
  'failed',
  'declined',
  '13',
  'Geçersiz Tutar',
  'Test Gateway',
  'Ziraat Bankası',
  'VISA',
  '7894',
  '454671',
  1,
  'TEST KULLANICI',
  '192.168.1.102',
  FALSE,
  20,
  'approved',
  'Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15',
  'sess_test_003',
  '{"card_number": "454671******7894", "cvv": "130", "amount": 1500.00, "currency": "TRY"}',
  '{"status": "failed", "code": "13", "message": "Geçersiz Tutar", "transaction_id": "TXN_FAILED_002"}',
  'Test: CVV 130 kullanıldı',
  NOW() - INTERVAL 15 MINUTE,
  NOW() - INTERVAL 15 MINUTE
);

-- Başarısız işlem - Fraud Şüphesi (CVV: 340)
INSERT INTO online_payment_transactions (
  registration_id,
  transaction_id,
  order_id,
  amount,
  currency,
  status,
  payment_status,
  error_code,
  error_message,
  gateway_name,
  bank_name,
  card_type,
  card_last4,
  card_bin,
  installment,
  cardholder_name,
  ip_address,
  is_3d_secure,
  fraud_score,
  fraud_status,
  user_agent,
  session_id,
  gateway_request,
  gateway_response,
  notes,
  initiated_at,
  created_at
) VALUES (
  1,
  'TXN_FAILED_003',
  'ORD_2024_006',
  2800.00,
  'TRY',
  'failed',
  'declined',
  '34',
  'Fraud Şüphesi',
  'Test Gateway',
  'Ziraat Bankası',
  'VISA',
  '7894',
  '454671',
  1,
  'TEST KULLANICI',
  '192.168.1.103',
  FALSE,
  85,
  'flagged',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  'sess_test_006',
  '{"card_number": "454671******7894", "cvv": "340", "amount": 2800.00, "currency": "TRY"}',
  '{"status": "failed", "code": "34", "message": "Fraud Şüphesi", "transaction_id": "TXN_FAILED_003"}',
  'Test: CVV 340 kullanıldı - Yüksek fraud skoru',
  NOW() - INTERVAL 25 MINUTE,
  NOW() - INTERVAL 25 MINUTE
);

-- Başarısız işlem - Çalıntı Kart (CVV: 370)
INSERT INTO online_payment_transactions (
  registration_id,
  transaction_id,
  order_id,
  amount,
  currency,
  status,
  payment_status,
  error_code,
  error_message,
  gateway_name,
  bank_name,
  card_type,
  card_last4,
  card_bin,
  installment,
  cardholder_name,
  ip_address,
  is_3d_secure,
  fraud_score,
  fraud_status,
  user_agent,
  session_id,
  gateway_request,
  gateway_response,
  notes,
  initiated_at,
  created_at
) VALUES (
  1,
  'TXN_FAILED_004',
  'ORD_2024_007',
  4200.00,
  'TRY',
  'failed',
  'declined',
  '37',
  'Çalıntı Kart',
  'Test Gateway',
  'Ziraat Bankası',
  'VISA',
  '7894',
  '454671',
  1,
  'TEST KULLANICI',
  '192.168.1.104',
  FALSE,
  95,
  'blocked',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
  'sess_test_007',
  '{"card_number": "454671******7894", "cvv": "370", "amount": 4200.00, "currency": "TRY"}',
  '{"status": "failed", "code": "37", "message": "Çalıntı Kart", "transaction_id": "TXN_FAILED_004"}',
  'Test: CVV 370 kullanıldı - Çalıntı kart listesinde',
  NOW() - INTERVAL 30 MINUTE,
  NOW() - INTERVAL 30 MINUTE
);

-- Başarısız işlem - Limit Yetersiz (CVV: 510)
INSERT INTO online_payment_transactions (
  registration_id,
  transaction_id,
  order_id,
  amount,
  currency,
  status,
  payment_status,
  error_code,
  error_message,
  gateway_name,
  bank_name,
  card_type,
  card_last4,
  card_bin,
  installment,
  cardholder_name,
  ip_address,
  is_3d_secure,
  fraud_score,
  fraud_status,
  user_agent,
  session_id,
  gateway_request,
  gateway_response,
  notes,
  initiated_at,
  created_at
) VALUES (
  1,
  'TXN_FAILED_005',
  'ORD_2024_008',
  8500.00,
  'TRY',
  'failed',
  'declined',
  '51',
  'Limit Yetersiz',
  'Test Gateway',
  'Ziraat Bankası',
  'VISA',
  '7894',
  '454671',
  1,
  'TEST KULLANICI',
  '192.168.1.105',
  FALSE,
  15,
  'approved',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  'sess_test_008',
  '{"card_number": "454671******7894", "cvv": "510", "amount": 8500.00, "currency": "TRY"}',
  '{"status": "failed", "code": "51", "message": "Limit Yetersiz", "transaction_id": "TXN_FAILED_005"}',
  'Test: CVV 510 kullanıldı - Kart limiti aşıldı',
  NOW() - INTERVAL 35 MINUTE,
  NOW() - INTERVAL 35 MINUTE
);

-- Bekleyen işlem
INSERT INTO online_payment_transactions (
  registration_id,
  transaction_id,
  order_id,
  amount,
  currency,
  status,
  payment_status,
  gateway_name,
  bank_name,
  card_type,
  card_last4,
  card_bin,
  installment,
  cardholder_name,
  ip_address,
  is_3d_secure,
  fraud_score,
  fraud_status,
  user_agent,
  session_id,
  gateway_request,
  initiated_at,
  created_at
) VALUES (
  1,
  'TXN_PENDING_001',
  'ORD_2024_004',
  4200.00,
  'TRY',
  'pending',
  'waiting',
  'Test Gateway',
  'Ziraat Bankası',
  'VISA',
  '7894',
  '454671',
  3,
  'TEST KULLANICI',
  '192.168.1.103',
  TRUE,
  10,
  'approved',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  'sess_test_004',
  '{"card_number": "454671******7894", "amount": 4200.00, "currency": "TRY", "installment": 3}',
  NOW() - INTERVAL 1 MINUTE,
  NOW() - INTERVAL 1 MINUTE
);

-- Başarılı işlem - MasterCard
INSERT INTO online_payment_transactions (
  registration_id,
  transaction_id,
  order_id,
  amount,
  currency,
  status,
  payment_status,
  gateway_name,
  bank_name,
  card_type,
  card_last4,
  card_bin,
  installment,
  cardholder_name,
  ip_address,
  is_3d_secure,
  threeds_status,
  eci,
  fraud_score,
  fraud_status,
  user_agent,
  session_id,
  gateway_request,
  gateway_response,
  initiated_at,
  completed_at,
  callback_received_at,
  created_at
) VALUES (
  1,
  'TXN_SUCCESS_002',
  'ORD_2024_005',
  5800.00,
  'TRY',
  'success',
  'approved',
  'Test Gateway',
  'İş Bankası',
  'MasterCard',
  '0006',
  '540036',
  6,
  'TEST KULLANICI',
  '192.168.1.104',
  TRUE,
  'Y',
  '02',
  8,
  'approved',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
  'sess_test_005',
  '{"card_number": "540036******0006", "amount": 5800.00, "currency": "TRY", "installment": 6}',
  '{"status": "success", "code": "00", "message": "İşlem başarılı", "transaction_id": "TXN_SUCCESS_002"}',
  NOW() - INTERVAL 20 MINUTE,
  NOW() - INTERVAL 18 MINUTE,
  NOW() - INTERVAL 18 MINUTE,
  NOW() - INTERVAL 20 MINUTE
);

-- İşlem logları ekle
INSERT INTO online_payment_logs (transaction_id, event_type, event_data, ip_address, user_agent)
SELECT id, 'initiated', '{"step": "payment_form_submitted"}', ip_address, user_agent
FROM online_payment_transactions
WHERE transaction_id IN ('TXN_SUCCESS_001', 'TXN_FAILED_001', 'TXN_FAILED_002', 'TXN_PENDING_001', 'TXN_SUCCESS_002');

INSERT INTO online_payment_logs (transaction_id, event_type, event_data, ip_address, user_agent)
SELECT id, 'callback', '{"step": "gateway_callback_received"}', ip_address, user_agent
FROM online_payment_transactions
WHERE transaction_id IN ('TXN_SUCCESS_001', 'TXN_SUCCESS_002');

INSERT INTO online_payment_logs (transaction_id, event_type, event_data, ip_address, user_agent)
SELECT id, 'success', '{"step": "payment_completed"}', ip_address, user_agent
FROM online_payment_transactions
WHERE status = 'success';

INSERT INTO online_payment_logs (transaction_id, event_type, event_data, ip_address, user_agent)
SELECT id, 'failed', CONCAT('{"step": "payment_failed", "error_code": "', error_code, '"}'), ip_address, user_agent
FROM online_payment_transactions
WHERE status = 'failed';
